### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jendrikseipp** [koehlma/pygtkspellcheck#26]
Thanks for maintaining this very useful API. I can't seem to find a changelog file though, listing the main changes between different versions.

**Comment by koehlma** [comment]
That's because such a file does not exist. However I follow semantic versioning so there are compatibility breaking changes between v3 and v4 anyway and version 4 had all it's features right from the beginning. Version 3 was mainly an intermediate version merging Carlos's fork into it. You might want to have a look at the commit history. Are there any specific changes you are interested in?

**Comment by jendrikseipp** [comment]
I think it would be very helpful to have such a file. Otherwise it is impossible to decide whether updating to a new version fixes bugs, adds features, breaks backwards compatibility, etc. For eample, at the moment I wouldn't be able to tell which changes I need to make to upgrade code from v3 to v4.

**Comment by koehlma** [comment]
I will consider adding such a file for future changes. 

>  Otherwise it is impossible to decide whether updating to a new version fixes bugs, adds features, breaks backwards compatibility, etc. For eample, at the moment I wouldn't be able to tell which changes I need to make to upgrade code from v3 to v4.
I am using [semantic versioning](http://semver.org/), so the version number as is tells you the type of changes.

**Comment by jendrikseipp** [comment]
Great, thanks!

**Comment by koehlma** [comment]
I added a changelog file. Although it is not very detailed (because I do not remember the exact changes regarding `oxt_extract`) it explains where the API incompatible changes occurred. A program running with version 3 not using `oxt_extract` will run with version 4 without any changes.

I will describe future changes regarding features and API changes in more detail.

**Comment by jendrikseipp** [comment]
Thanks!
