### ISSUE TITLE
Words containing an apostrophe are not treated as words

### ISSUE THREAD

**Issue by eternaldensity** [koehlma/pygtkspellcheck#33]
For example, the word "wasn't" is not treated as a word, instead "wasn" is matched and reported as an error (unless "wasn" is added to the dictionary, which should not be necessary since "wasn't" is a word but "wasn" is not).

**Comment by koehlma** [comment]
Since word separation is done by Pango this seems to be an issue with Pango:
https://developer.gnome.org/gtk3/stable/GtkTextIter.html#gtk-text-iter-forward-word-end

It should be possible to hack a fix into GtkSpellcheck, however I think this should rather be fixed in Pango itself. I will investigate further when I have the time.

**Comment by Dave-ts** [comment]
Any intended progress on this issue? I know this repo has been inactive for a while, are you planning to continue work on it?
